// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI-powered tool to categorize vehicle service records.
 *
 * - categorizeService - A function that classifies a service description into a predefined category.
 * - CategorizeServiceInput - The input type for the categorizeService function.
 * - CategorizeServiceOutput - The return type for the categorizeService function.
 */

import {ai} from '@/ai/genkit';
import { ServiceCategoryEnum } from '@/lib/types';
import {z} from 'genkit';

const CategorizeServiceInputSchema = z.object({
  serviceDescription: z.string().describe("A short description of the service performed on a vehicle, e.g., 'Oil Change', 'Replaced front brake pads and rotors'."),
});
export type CategorizeServiceInput = z.infer<typeof CategorizeServiceInputSchema>;

const CategorizeServiceOutputSchema = z.object({
  category: ServiceCategoryEnum.describe("The predicted category for the service."),
});
export type CategorizeServiceOutput = z.infer<typeof CategorizeServiceOutputSchema>;

export async function categorizeService(input: CategorizeServiceInput): Promise<CategorizeServiceOutput> {
  return categorizeServiceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeServicePrompt',
  input: {schema: CategorizeServiceInputSchema},
  output: {schema: CategorizeServiceOutputSchema},
  prompt: `You are an expert automotive service categorizer for both ICE and EV vehicles. Your job is to classify a service record into one of the following categories:
- Routine Maintenance: Regular, scheduled services like oil changes, fluid checks, filter replacements, battery health checks.
- Repairs: Fixing something that is broken or malfunctioning, like replacing a water pump, fixing a leak, or electrical repairs.
- Tires: Anything related to tires, such as tire rotation, new tires, or alignment.
- Inspection: A service that is primarily for inspection purposes.
- Other: Anything that doesn't fit into the above categories, like cosmetic work.

EV-specific examples of 'Routine Maintenance': "High Voltage Battery Coolant Service", "Drive Unit Fluid Change".

Classify the following service:
Service Description: "{{{serviceDescription}}}"
`,
});

const categorizeServiceFlow = ai.defineFlow(
  {
    name: 'categorizeServiceFlow',
    inputSchema: CategorizeServiceInputSchema,
    outputSchema: CategorizeServiceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
